language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      env: CC=clang-4.0 CXX=clang++-4.0 BUILD_TYPE=Debug
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - ninja-build
            - libboost-all-dev

    - os: linux
      dist: trusty
      sudo: false
      env: CC=clang-5.0 CXX=clang++-5.0 BUILD_TYPE=Debug
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - ninja-build
            - libboost-all-dev

    - os: linux
      dist: trusty
      sudo: false
      env: CC=gcc-6 CXX=g++-6 BUILD_TYPE=Debug
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - ninja-build
            - libboost-all-dev

    - os: linux
      dist: trusty
      sudo: false
      env: CC=gcc-7 CXX=g++-7 BUILD_TYPE=Debug
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - ninja-build
            - libboost-all-dev

    - os: osx
      osx_image: xcode9.3
      env: BUILD_TYPE=Debug


before_install:
  - |
      if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
        brew update
      fi

install:
  - |
      if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
        brew install boost
        brew install ninja
      fi

script:
  - mkdir bin
  - cd bin
  - cmake -GNinja -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..
  - cmake --build . --target all
  - ctest --verbose

