language: cpp

dist: trusty
sudo: true

compiler:
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
      - libboost-all-dev
      - ninja-build
      - doxygen

#before_install:
#  - sudo apt-get -qq update
#  - sudo apt-get install -y cmake ninja-build doxygen

script:
  - cmake -GNinja
  - cmake --build . --target all

