language: cpp

os: linux
dist: trusty
sudo: false

matrix:
  include:
    - env: COMPILER=clang++-4.0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - ninja-build
            - libboost-all-dev

    - env: COMPILER=clang++-5.0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - ninja-build
            - libboost-all-dev

    - env: COMPILER=g++-6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - ninja-build
            - libboost-all-dev

    - env: COMPILER=g++-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - ninja-build
            - libboost-all-dev

install:
  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi
  - ${CXX} --version

script:
  - mkdir bin
  - cd bin
  - cmake -GNinja ..
  - cmake --build . --target all
  - ctest --verbose

