language: cpp

os: linux
dist: xenial
sudo: false

matrix:
  include:
    - env: COMPILER=clang++-4.0 BUILD_TYPE=Debug
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - ninja-build
            - libboost-all-dev

    - env: COMPILER=clang++-5.0 BUILD_TYPE=Debug
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - ninja-build
            - libboost-all-dev

    - env: COMPILER=g++-6 BUILD_TYPE=Debug
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - ninja-build
            - libboost-all-dev

    - env: COMPILER=g++-7 BUILD_TYPE=Debug
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - ninja-build
            - libboost-all-dev

install:
  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi
  - ${CXX} --version

script:
  - mkdir bin
  - cd bin
  - cmake -GNinja -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..
  - cmake --build . --target all
  - ctest --verbose

