image: lukaszlaszko/build_tools_clang_3_9:latest

pipelines:
  default:
    - step:
        script:
            - git submodule update --init
            - mkdir bin
            - pushd bin
            - cmake -GNinja -DCMAKE_C_COMPILER=clang-3.9 -DCMAKE_CXX_COMPILER=clang++-3.9 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS='-fprofile-instr-generate -fcoverage-mapping' -DCMAKE_EXE_LINKER_FLAGS='-fprofile-instr-generate -fcoverage-mapping' ..
            - cmake --build . --target all
            - ctest --verbose
            - cd tests
            - llvm-profdata-3.9 merge -sparse default.profraw -o default.profdata
            - llvm-cov-3.9 report ./tests --instr-profile=default.profdata
            - popd
            - timeout 1m external/scripts/docs/build_docs.sh -t bin_docs
            - timeout 1m external/scripts/docs/push_docs.sh -c -r git@bitbucket.org:lukaszlaszko/lukaszlaszko.bitbucket.org.git -d bin_docs/*