image: lukaszlaszko/build_tools_clang_3_9:latest

pipelines:
  default:
    - step:
        script:
          - mkdir bin
          - cd bin
          - cmake -GNinja -DCMAKE_C_COMPILER=clang-3.9 -DCMAKE_CXX_COMPILER=clang++-3.9 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS='-fprofile-instr-generate -fcoverage-mapping' -DCMAKE_EXE_LINKER_FLAGS='-fprofile-instr-generate -fcoverage-mapping' ..
          - cmake --build . --target all
          - ctest --verbose
          - cd tests
          - llvm-profdata-3.9 merge -sparse default.profraw -o default.profdata
          - llvm-cov-3.9 report ./tests --instr-profile=default.profdata
          
  branches:
    feature-add-doxygen-support:
        - step:
            script:
                - mkdir bin
                - cd bin
                - cmake -GNinja -DCMAKE_C_COMPILER=clang-3.9 -DCMAKE_CXX_COMPILER=clang++-3.9 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS='-fprofile-instr-generate -fcoverage-mapping' -DCMAKE_EXE_LINKER_FLAGS='-fprofile-instr-generate -fcoverage-mapping' ..
                - cmake --build . --target all
                - ctest --verbose
                - cd tests
                - llvm-profdata-3.9 merge -sparse default.profraw -o default.profdata
                - llvm-cov-3.9 report ./tests --instr-profile=default.profdata
                - cd ../..
                - echo $PRIVATE_KEY > ~/.ssh/id_rsa.tmp
                - base64 -d ~/.ssh/id_rsa.tmp > ~/.ssh/id_rsa
                - chmod 600 ~/.ssh/id_rsa
                - base64 ~/.ssh/id_rsa
                - git clone git@bitbucket.org:lukaszlaszko/lukaszlaszko.bitbucket.org.git bin_doc
                - docs/build_docs.sh -t bin_doc
                - cd bin_doc
                - git add -all
                - git commit -m "docs for $BITBUCKET_COMMIT"
                - git push
  tags:
    release-*:
        - step:
            script:
                - mkdir bin
                - cd bin
                - cmake -GNinja -DCMAKE_C_COMPILER=clang-3.9 -DCMAKE_CXX_COMPILER=clang++-3.9 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS='-fprofile-instr-generate -fcoverage-mapping' -DCMAKE_EXE_LINKER_FLAGS='-fprofile-instr-generate -fcoverage-mapping' ..
                - cmake --build . --target all
                - ctest --verbose
                - cd tests
                - llvm-profdata-3.9 merge -sparse default.profraw -o default.profdata
                - llvm-cov-3.9 report ./tests --instr-profile=default.profdata
                - cd ../..
                - mkdir bin_doc
                - cd bin_doc
                - doxygen ../docs/doxygen.cfg